apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-server-pv
  namespace: monitoring  
  labels:
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/name: alertmanager
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/prometheus-server/data"
