apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage-prometheus-alertmanager-pv
  namespace: monitoring  
  labels:
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/name: alertmanager
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/prometheus/data"
