apiVersion: v1
data:
  web-config.yaml: |
    # TLS and basic authentication configuration example.
    #
    # Additionally, a certificate and a key file are needed.
    tls_server_config:
      cert_file: /etc/prometheus/tls/tls.crt
      key_file: /etc/prometheus/tls/tls.key

    # Usernames and passwords required to connect to Prometheus.
    # Passwords are hashed with bcrypt: https://github.com/prometheus/exporter-toolkit/blob/master/docs/web-configuration.md#about-bcrypt
    basic_auth_users:
      alice: $2y$10$mDwo.lAisC94iLAyP81MCesa29IzH37oigHC/42V2pdJlUprsJPze
      bob: $2y$10$hLqFl9jSjoAAy95Z/zw8Ye8wkdMBM8c5Bn1ptYqP/AXyV0.oy0S8m
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: web-config
  namespace: monitoring
