apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-loki-read-0
  namespace: monitoring
  labels:
    app.kubernetes.io/name: loki
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem    
  hostPath:
    path: "/mnt/promdata"
