---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-grafana
  namespace: monitoring
  labels:
    app: grafana
spec:
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: myhome
  hostPath:
    path: "/mnt/grafana/data"
