---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-grafana
  namespace: monitoring
  labels:
    app: grafana
spec:
  storageClassName: myhome
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
