apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      name: grafana
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        ports:
        - name: grafana
          containerPort: 3000
        resources:
          limits:
            memory: "1Gi"
            cpu: "1000m"
          requests: 
            memory: 500M
            cpu: "500m"
        volumeMounts:
          - name: grafana-certs
            mountPath: /etc/grafana/certs/
            readOnly: true
          - name: grafana-storage            
            mountPath: /var/lib/grafana
          - name: grafana-config
            mountPath: /etc/grafana  
          - name: grafana-datasources            
            mountPath: /etc/grafana/provisioning/datasources
            readOnly: false
      volumes:
        - name: grafana-config
          configMap:
            name: grafana-ini
        - name: grafana-storage
          emptyDir: {}
        - name: grafana-datasources
          configMap:
              defaultMode: 420
              name: grafana-datasources
        - name: grafana-certs
          secret:
            secretName: grafana-tls
            items:
            - key: tls.crt
              path: tls.crt
            - key: tls.key
              path: tls.key              
