apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-loki-write-0-pv
  namespace: monitoring  
  labels:
    app.kubernetes.io/component: write
    app.kubernetes.io/instance: loki
    app.kubernetes.io/name: loki
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/loki-write-0/data"
