apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage-loki-1-pv
  namespace: loki  
  labels:
    app.kubernetes.io/component: single-binary
    app.kubernetes.io/instance: loki
    app.kubernetes.io/name: loki
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/storage-loki/data"
