minio:
  enabled: false
loki:
  auth_enabled: false 
  storage_config:
    boltdb_shipper:
      active_index_directory: /var/loki/index
      cache_location: /var/loki/index_cache
      resync_interval: 5s
      shared_store: s3
    aws:
      s3: http://admin:xxxxxxxxx@minio.minio.svc.cluster.local.:9000/loki
      s3forcepathstyle: true
commonConfig:
  replication_factor: 2 
write:
  replicas: 2
read:
  replicas: 2 
backend:
  replicas: 2  
